plugins:
  DiscourseDesignBundles_api_url:
    type: string
    default: ''
  DiscourseDesignBundles_css_url:
    type: string
    default: ''
  DiscourseDesignBundles_hash_key:
    type: string
    default: ''
  DiscourseDesignBundles_trusted_affiliates:
    type: string
    default: ''
  DiscourseDesignBundles_enabled:
    default: true